### ISSUE TITLE
PRIO 1 - iOS - Ticketing - provide Ok button for going back to app main screen after successful validation of certificate 

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-ios#111]
iOS wallet app 1.2.2.1 (3) acc
iPad 11 Pro

**expected result**
There should be an OK oe Close button to go back to the main screen of the wallet app

**actual result**
confirmation screens stays open and I had to kill the app

![image](https://user-images.githubusercontent.com/81565834/138251167-b6d6932f-b5f0-4f24-ad5d-dd0d9f02d9aa.png)

sample from Android:
![image](https://user-images.githubusercontent.com/81565834/138251352-55b703cf-f9b4-41f0-bbfa-d2c3a36a9249.png)

**Comment by ivlasov** [comment]
There was a button :) I will fix it)

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment]
Can we have an okay Button that leads directly to the HomeScreen (the Certificate-Overview) like in the Android Version?
