### ISSUE TITLE
PRIO - Certificate for Ticketing can not be found

### ISSUE THREAD

**Issue by Hendrik-Schmidt-Schierhorn-TSI** [eu-digital-green-certificates/dgca-wallet-app-ios#121]
## Describe the bug

After scanning the Code from the Booking-Portal and selecting an endpoint, the related certificate does not show up in the List of certificates.

![IMG_0111](https://user-images.githubusercontent.com/81570419/141746208-5b8934b7-0f8d-4e19-bd0d-e5e3e46f9a21.PNG)
## Expected behaviour

With the same booking code and the same certificate, the certificate is visible on android:
![Screenshot_20211115-085055_Wallet App](https://user-images.githubusercontent.com/81570419/141746604-8bd7c514-8a16-4fce-9c67-c9004ddb6cee.jpg)

## data used for test

![dcc_booking_issue1](https://user-images.githubusercontent.com/81570419/141747215-3a300cd7-0e77-4ece-a565-8697598ebbc7.JPG)

![dcc_booking_issue2](https://user-images.githubusercontent.com/81570419/141747227-bf1328ed-ed99-4481-9f10-4270108097f8.JPG)

![dcc_booking_issue3](https://user-images.githubusercontent.com/81570419/141747252-806e73c1-5e4b-4934-83a1-a0baccb63ade.JPG)
- Host Machine OS (Windows/Linux/Mac):

## Technical details
 - iPhoneX
 - iOS 14.4
 - Version 1.2.3.1 (5)

**Comment by kerstin-oppermann-tsi** [comment]
fixed in wallet 1.2.3(6)
