### ISSUE TITLE
Not able to build this project

### ISSUE THREAD

**Issue by sehaswaran** [eu-digital-green-certificates/dgca-wallet-app-ios#125]
Receiving this error

No type named 'ScanVC' in module 'SwiftDGC'

In SwiftDGC Package, we couldn't find ScanVC,ScanVCDelegate. 

Could you please help to run this app ?

**Comment by PaulBallmann** [comment]
Please make sure to import the core module as well. https://github.com/eu-digital-green-certificates/dgca-app-core-ios
