### ISSUE TITLE
[Prio iOS Wallet App] No Indication of "Revoked" Certificates

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-ios#132]
![VAC_C1](https://user-images.githubusercontent.com/76050122/157637552-bb31512f-a70c-42f9-af32-09428c425ba1.png)
Revoked certificates are not always shown as revoked on some devices as expected.
This problem could mostly be resolved with the workaround by scrolling or by reload. But it does not guarantee that it would work.
## Expected behaviour
At least in the list view after scrolling or reloading multiple times there should be some indication of revoked certificates.

## Steps to reproduce
1. Claim the following certificate (which is revoked); The current TAN for claiming this certificate is: M36Z2V7D
2. Press reload in app settings;
3. Scroll up and down the certificate list.  => no indication of "revoked" is to be seen.

## Technical Details
iOS Wallet App 1.3.1 (5) tst
iPhone 8 plus v. Lutz, iOS 15.3.1

**Comment by michawol** [comment]
war: GTAS7M6F
neu: M36Z2V7D

**Comment by michawol** [comment]
neu: YN44D5S5

**Comment by RalicaY** [comment]
Neue TAN: N32K92AX

**Comment by RalicaY** [comment]
iPhone 8 plus v. Lutz, IOS 15.3.1 : VAC_C1 revocation view failed for this device 

iPhone 7, IOS 15.3.1 : VAC_C1 revocation view passed with workaround (push to refresh)

**Comment by PaulBallmann** [comment]
Unable to save the certicate with given TAN: N32K92AX

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY can you check again this issue with new release 1.3.1.(7)

**Comment by RalicaY** [comment]
Yes, retest with the latest iOS Wallet App 1.3.1 (7) was successful!

**Comment by RalicaY** [comment]
I have moved the issue back to open, since we have so far only successfully tested it for Hash-List.  As soon we can confirm the successful test for Bloom Filter also, I will close the issue.

**Comment by RalicaY** [comment]
Successfully tested for iOS against Bloom Filter Backend.
