### ISSUE TITLE
[iOS Wallet App] - Lost all certs when updating app

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-ios#133]
## Describe the bug
When updating the app from an earlier version, all claimed certs are lost

## Expected behaviour
After updating, all aready claimed certs are still in the cert list

## Steps to reproduce the issue
1.  install a previous version
2. claim some certs
4. update to the new app

several update attempts were unsuccessful

## Technical details

- Host Machine OS (Windows/Linux/Mac):
iPhone 7, IOS 15.3.1
WalletApp 1.3.1 (5)

**Comment by PaulBallmann** [comment]
This behaviour is expected due to the update mechanism of AppCenter. It is advised to please uninstall the app before installing the new update anyways. Please close this issue.

**Comment by kerstin-oppermann-tsi** [comment]
@michawol see @PaulBallmann 's comment
