### ISSUE TITLE
[iOS Wallet] newly revoked cerificate will not be updated in certificate list

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-ios#135]
When certificate is already claimed to wallet app and will be revoked later, the revokation status is not updated.

1. Claim valid certificate
2. Revoke certificate
3. Wait about 10 minutes
4. Update revokation status in settings menu
5. Scroll down certificate list

**Expected result:**
certificate should be shown as revoked

**Actual result:**
certificate is shown as valid

6. Claim the certificate again to app
-> certificate is shown as revoked

**Comment by PaulBallmann** [comment]
Addressed in 1.3.2 (1).

**Comment by kerstin-oppermann-tsi** [comment]
Will check with a cerificate claimed to wallet that expires 30/03/22 9 a.m.

**Comment by kerstin-oppermann-tsi** [comment]
feature works with 1.3.2(2)
