### ISSUE TITLE
[iOS-Wallet-App] Revocation Entry has Expired but Wallet App still Evaluates DCC-Code as REVOKED when they were stored before expiring

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-ios#136]
If a revoked cerificate expires while it is stored in the wallet, then this is shown as revoked after the expiration date too although the reload button is pressed.

**Expected behaviour:**
Certificates should be shown as valid after reloading the settings menu and refreshing the overview screen.

**Comment by kerstin-oppermann-tsi** [comment]
Issue is fixed in Version 1.3.2 (4).

**Comment by kerstin-oppermann-tsi** [comment]
Issue is not working anymore in 1.3.2(4) :(

**Comment by RalicaY** [comment]
The issue still persists in 1.3.3 (7)

**Comment by kerstin-oppermann-tsi** [comment]
@PaulBallmann can you have a look on this again?

**Comment by kerstin-oppermann-tsi** [comment]
Retest 11.5.2022 mit 1.3.3(11)

2 Zertifikat revoked. - Update in der App auf revoked Status hat super geklappt bei beiden. :white_check_mark:

Zertifikat expired 14:45 -> 14:49 Uhr in der wallet app Liste reloaded - Zertifikat wieder valid :white_check_mark:
Zertifikat expired 15 Uhr -> 15:13 Uhr ist das Zertifikat immer noch als revoked angezeigt :no_entry: trotz mehrmaligen reload in settings und im Overview -  die verifier app zeigt es auch als valid an

14:35 Uhr:
![image](https://user-images.githubusercontent.com/81565834/167859086-99edff7c-c5d7-4dc4-91e7-736ed52701f0.png)

15:18 Uhr:
![image](https://user-images.githubusercontent.com/81565834/167859471-0fa5e940-5c0b-44e0-b083-688d5f7ef2c1.png)

**Comment by kerstin-oppermann-tsi** [comment]
We have an idea, that the issue can be, if the certificate was claimed when it was already revoked and then expires it doesn't work. But if the certificate revokes while it is already claimed as a valid, and the expires, then this issue here works. But we have to investigate in this.

**Comment by kerstin-oppermann-tsi** [comment]
Seems to be the fact for now and in my testing cases:

When new revoked certificate is claimed or a further claimed certificate will change its status to revoked in app, THEN all expired certificates appear as valid. 

If nothing new happens in app, THEN all expired certificates stay in status expired.

**Comment by kerstin-oppermann-tsi** [comment]
Issue is fixed in wallet 1.3.3(14), successfully retested. After reload in settings menu the revoked expire certificates will no longer be shown as revoked in app.

**Comment by kerstin-oppermann-tsi** [comment]
@ltranvan can you recheck or set this issue to done.
