### ISSUE TITLE
[iOS-Wallet-App] qr-code are not recognizes

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-ios#139]
## Describe the bug
the scanned qr-code are not recognized. The app stay sill in scan mode

## Expected behaviour
The system recognizes that the signature was invalid and responds with a corresponding message

## Steps to reproduce the issue
1. scan the code
2. the app still in scan mode

## Technical details
iPhone 7, IOS 15.3.1
WalletApp 1.3.3 (4)

![nullable_values](https://user-images.githubusercontent.com/97519435/165467916-082b57b2-1d3a-44fa-99cc-fe2cd5883f3b.PNG)

**Comment by RalicaY** [comment]
Closed because it doubles https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/140
