### ISSUE TITLE
[iOS-Wallet-App] Nullable Values in Verifieable Credentials Lead To Unscannable Code

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-ios#140]
## Describe the bug

We tried to can a Verifiable Credential Code with Null-values.  The app could not read the code.  It was not scannable.  (See attached code).

## Expected behaviour

The app should be able to scan such codes.

## Technical details
iOS Wallet App 1.3.3(4)
![nullable_values](https://user-images.githubusercontent.com/76050122/165501387-3e3be98e-7d1d-4542-a626-de55ed63f138.PNG)

**Comment by RalicaY** [comment]
Retest failed, scanning same code results to "Cannot read barcode", iOS Wallet 1.3.3(7)

**Comment by MykhailoNester** [comment]
<img width="642" alt="Screenshot 2022-05-10 at 12 25 31" src="https://user-images.githubusercontent.com/9447674/167596287-aeaf4e6f-d787-4867-bb9f-ff394437ba29.png">

**Comment by ltranvan** [comment]
tvt, 11.05.2022:
The same code scanned bei Android-Verifier and bring an another message, but
at the end the JWT and not the verifiable Credential is noticed by the app and an error-message is displayed
