### ISSUE TITLE
[iOS-Wallet-App] Dont accept the generated TAN

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-ios#141]
## Describe the bug
a new generated certificate (VAC, Test) from the web page cannot store in the App
because the tan are not accepted

## Expected behaviour
after accepting the TAN, the certificate is claimed

## Steps to reproduce the issue
1. Create a certificate in the web app
2. scan the qr-code with the wallet app
3. click save
4. enter the tan whis is shown at the web page

## Technical details
- iPhone 7, IOS 15.3.1
- WalletApp 1.3.3 (4)

**Comment by michawol** [comment]
fixed with 

DGCA Wallet
--
1.3.3 (5)
for iOS

**Comment by RalicaY** [comment]
retest failed iOS Wallet 1.3.3(7)  No new TAN is shown for claimed certificates. I.e., once a certifificate is claimed with the original TAN, there is no new TAN generated and therefore the Code cannot be claimed again.

**Comment by RalicaY** [comment]
Indeed, fixed

**Comment by RalicaY** [comment]
I deleted my previous comment because it was in the wrong ticket. This one must remain closed.
