### ISSUE TITLE
[iOS-Wallet-App] LOW PRIO: dont request a biometric / pin code when started

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-wallet-app-ios#142]
## Describe the bug
when starting the app, its show directly the list of certicated.
no biometric / pin is requested

## Expected behaviour
after starting, it must be enter a biometric or pin code befor showing the certicate list

## Steps to reproduce the issue

1. start the app

## Technical details
iPhone 7, IOS 15.3.1
WalletApp 1.3.3 (4)

**Comment by RalicaY** [comment]
Successfully retested iOS Wallet 1.3.3(7)
