### ISSUE TITLE
Will a beta version via testflight available before the release?

### ISSUE THREAD

**Issue by ouboub** [eu-digital-green-certificates/dgca-wallet-app-ios#29]
Hi

I would be interested in testing the beta version, if possible since I will travel frequently between Germany and Spain

regards

Uwe Brauer

**Comment by yspreen** [comment]
@ouboub Luckily, that's not the case. See [here](https://ionicframework.com/blog/deploying-to-a-device-without-an-apple-developer-account/) for example.

**Comment by ouboub** [comment]
>>> "YS" == Yannick Spreen ***@***.***> writes:

> @ouboub Luckily, that's not the case. See
> [here](https://ionicframework.com/blog/deploying-to-a-device-without-an-apple-developer-account/)
> for example.

Thanks! (I still think a public testflight version would be great (I am
doing this already for a couple, of commercial apps), but that solution
is better than nothing). I will try it out as soon as I can.

The release date is still the beginning of June?

**Comment by yspreen** [comment]
I'm still a bit concerned about your test case here. The fact that you plan to travel doesn't have anything to do with testing the features of this app. The wallet stores certificates, yes, but they aren't issued yet. We're in the development phase.

We're welcoming any feature requests and bug reports with open arms, but using this application for traveling is not in the scope of the project right now, nor will it ever be. The EU member states will have to adapt the template we're building here to deploy real working verifier and wallet apps. We're just providing a dev environment.

**Comment by ouboub** [comment]
ah ok, this was not entirely clear to me. Can you provide me any pointers to repositories of the corresponding states?
I am a bit confused, since it was announced  that a a full functional app to be released in June (not sure whether beginning or end), 
but given the fact that for example the development of the covid warn apps in Spain was quite  bit behind that of Germany (I can tell that with some confidence since I participated in the discussions in both repos, asking for additional features. I am now rather skeptical that this time schedule can be met.
