### ISSUE TITLE
Support reading of multi entry certificates

### ISSUE THREAD

**Issue by advatar** [eu-digital-green-certificates/dgca-wallet-app-ios#48]
## Current Implementation

Only the last HCertEntry is displayed

## Suggested Enhancement

Would be good to be able to see all of the contents. It seems to me that core does not support this at the moment.

## Expected Benefits

Would be good to be able to see all of the contents. You might f.i have had only one shot but have a negative PCR test.

**Comment by yspreen** [comment]
The current spec only supports 1 statement. If you wish to include multiple, I think the spec repo would be a better place for that. Maybe https://github.com/ehn-digital-green-development/ehn-dgc-schema ?

**Comment by yspreen** [comment]
This repo is definitely the wrong place. If you feel like this is a problem of the Swift implementation, that we're not following the spec, please reopen in the core module. Thanks
