### ISSUE TITLE
no app start on IOS 12

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-ios#50]
## Describe the bug

I just started the IPhone to be sure no service is running anymore. Installing the Version 1.0 of the walletApp. After that i tried to start the App but I get just a black screen.
On IPhone Xs everything works fine.

## Expected behaviour

The App should start

## Steps to reproduce the issue

1. restart the IPhone
2. install version 1.0 from AppCenter
3. trust the Application in IPhone settings
4. start WalletApp
5. just a black screen is shown

## Technical details
IPhone 6
IOS-Version 12.5.1

**Comment by yspreen** [comment]
we need someone with an old iPhone and developer tools to debug this. I don't have such an old device for testing :/

**Comment by rebwalz** [comment]
> we need someone with an old iPhone and developer tools to debug this. I don't have such an old device for testing :/

maybe it is possible to get one from the development team?

**Comment by yspreen** [comment]
I found the issue, it's because of iOS 12. Will work on a fix as 1.1.0
