### ISSUE TITLE
Two Fields named "Time of Sampling" in Certificate of Type TEST

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-ios#51]
![Time_of_Sampling_Wallet_iOS](https://user-images.githubusercontent.com/76050122/119678211-a37c9500-be3f-11eb-8ec2-85347d05d618.jpg)

## Describe the bug

There are two fields named "Time of Sampling" shown in the certificate data in certificates of type TEST. 

## Expected behaviour

One of these two "Time of Sampling" fields contains the value "Detected/Undetected" and should be called "Test Result".

## Steps to reproduce the issue

Read a Test Certificate in the wallet app.

## Technical details

iPhone 8 plus v. Lutz,  Model MQ8P2ZD/A, iOS 14.4

**Comment by yspreen** [comment]
This is probably related to the wrong core module being built. Please check with Hendrik that you're using the latest build

**Comment by rebwalz** [comment]
In latest release, it could be retestet successful.
