### ISSUE TITLE
Shortly shows certificate, then disappears again

### ISSUE THREAD

**Issue by frogg** [eu-digital-green-certificates/dgca-wallet-app-ios#55]
## Describe the bug
See attached video. After granting the camera permissions, the certificate shows up briefly and then disappears again.

## Expected behaviour
The certificate shouldn't disappear right after it appeared.

## Steps to reproduce the issue
This seems to be related to #54.

## Technical details
iPhone XS, iOS 14.5.

## Possible Fix
change the code

## Additional context

https://user-images.githubusercontent.com/5204169/118958672-ec28df80-b961-11eb-9b66-cc68af3731d7.mov

**Comment by yspreen** [comment]
I think 1.0.1 closes this issue. If not, please open again. Thanks @frogg
