### ISSUE TITLE
all TANs not found after changing IssuerWebApp URL

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-ios#57]
## Describe the bug

After changing the IssuerWebApp to another URL, no TANs are found to claim the qr-code

## Expected behaviour

valid TAN should claim the qr-code

## Steps to reproduce the issue

1. open WalletApp 
2. unlock via faceID
3. push the button "Scan code"
4. qr-code will be scaned
5. qr-code details will be shown
6. push "save"
7. TAN is requested
8. insert valid TAN
9. see error message: Failure: Check the TAN and try again

## Technical details

- Host Machine OS (Windows/Linux/Mac):
- IOS Xs IOS 14.4

**Comment by frogg** [comment]
I had the same issue, but only after I‘ve added, deleted, and then scanned the same code again. Maybe that's helpful.

**Comment by rebwalz** [comment]
> I had the same issue, but only after I‘ve added, deleted, and then scanned the same code again. Maybe that's helpful.

no, that didn't help.
