### ISSUE TITLE
Deep-Link functionality

### ISSUE THREAD

**Issue by rebwalz** [eu-digital-green-certificates/dgca-wallet-app-ios#60]
## Your Question
in User Story 2: Import Green Certificate in the Wallet App, is a second optionally way to import the cerificate by a deep link which was sended by SMS or email.

> Optionally you can use a deep link instead of a 2D Code to initiate the certificate import in the
wallet app. The deep link can look like:
dgc://example.authority.com?token=ey… & [publickey]
In this case the token is received with the link, and the public key must be replaced by the key
of the new generated key pair of the certificate container in the wallet app. The deep link can
be delivered by SMS, Email or by presenting another 2D Code for scan. 

You find it in specification: [https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v4_en.pdf](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-certificates_v4_en.pdf) on page 12

* Question: When will it be implemented?

**Comment by yspreen** [comment]
You'll have to ask the project lead. They dont read issues here.

It's not part of the current release schedule.

**Comment by SchulzeStTSI** [comment]
@rebwalz The deeplink feature is not scope of the implementation, but it was recommended as guideline for the MS (so far possible).

**Comment by yspreen** [comment]
If I understand it correctly, since it's currently not on our timeline, this issue is not applicable yet. So I'll close for now
