### ISSUE TITLE
Security Concern - Showing Personal Data prior to requesting the TAN - Not consistent with Android Version

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-wallet-app-ios#75]
Dear Team, 

The iOS Wallet allows the scanning of the QR Code, and shows personal data, without requesting the TAN first.
On Android, the Wallet requires the TAN prior to showing personal data.

Please can this be iOS Wallet implementation be aligned with the Android implementation with regard to showing the Personal Data prior as first ask and validate the TAN, prior to showing the Personal Data.

Best Regards
Panayiotis Savva

**Comment by PaulBallmann** [comment]
Hello,

thank you for your feedback. However, according to the DGC spec, this is implemented as intended. The TAN is used for adding the certificate into the wallet, not for unlocking its data. Therefore, we will not be changing the behaviour. We will align with our Android colleagues to streamline the process of adding your certificate to wallet according to spec.

Kind regards,
Paul

**Comment by psavva** [comment]
Opened a new issue for the Point of Alignment.

https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/80
