### ISSUE TITLE
Automatically Remove Expired Certificates

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-wallet-app-ios#76]
The request is to have expired certificates automatically purged from the Wallet.

Display the Expiry Date on the main screen that shows all loaded certificates as to ensure the holder is aware of when the specific certificate expires.

It also has the benefit of not holding this information (even for spouse or dependents, parents, etc.) once they expire, and thus no longer useful. This is a security consideration.

Same is requested for Android:
https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/issues/54

**Comment by PaulBallmann** [comment]
This would mean that certificates that might still be valid will be removed from the wallet. E.g. a test result that just is 24h and 1 second old. Some organisations might still accept it. Also, a vaccination certificate that might still be valid if the STIKO changes something will be automatically removed from the wallet. I could not see anything in the scope from the EU that indicates such a feature. Therefore, I will close this issue now. If I missed it in the scope please let me know by re-opening this issue.
