### ISSUE TITLE
Anonymized QR codes that works with wallet (and verifier)

### ISSUE THREAD

**Issue by majirosstefan** [eu-digital-green-certificates/dgca-wallet-app-ios#79]
Hi all, big thanks to all for making this project open-source.

Slovakia e.g. declares to have functionality that allows **wallet app to share/display QR codes with 'anonymized' data** (my guess is that the QR e.g. does not contain a person's name or date of birth).

I am interested only in the **technical point of view** of this question - so do you know about ways how this could be accomplished, please?

I checked the default JSON schema, where "**nam**" (person's surname and given name) and "**dob**" are required.

So I think the only way, how this could be accomplished, is that issuer would always issue 2 kinds/2 versions of certificates for a single test, single vaccination, or single recovery "event":

-one anonymized where the personal data fields would be just placeholders / containing dummy values to pass JSONSchema validation step
-and the second, with original personal data

I see no point, in a solution where the wallet removes personal data (like 'tampering certificate'), as the signature for the verifier would become invalid.

Could you suggest other ideas (if any) / or tell me if I am wrong somewhere with the solution above, please?

I am not a representative, nor a member of any official working group - so I do not want to waste the time of any of you if you are currently under pressure.

Thanks.

**Comment by grischard** [comment]
I am also not a representative, nor a member of any official working group.

The signature would indeed become invalid if fields are redacted or removed. The issuer could issue two codes - one anonymous and one with full information - but then no one can check if the certificate I'm showing on my phone is mine or yours, no?

**Comment by daniel-eder** [comment]
As far as I understand this is not part of the specification and functionality the EU provides to the member states, so it is to my understanding somewhat out of scope for this project.

I agree with the assessment, that removing data after the fact will invalidate the signature. 

It may be best to get directly in touch with the member states that implement such a system to get information on how they plan to enable this functionality.

**Comment by PaulBallmann** [comment]
As Daniel already mentioned, this is not part of the specification from the EU. Also, as you already pointed out, it does not make sense for the verifier or wallet to omit those personal fields. Furthermore, it would not be possible to distinguish if it is my certificate or someone else's. For that reason, I will close this issue now.
