### ISSUE TITLE
Streamline iOS and Android impelemtnations with regards to TAN Input

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-wallet-app-ios#80]
Please align with the Android team to streamline the process of adding a certificate to a wallet according to spec.

Currently there is a misalignment where Data is shown first in iOS, then TAN is required.
In Android, TAN is requested, then Data is shown.

Please can these two be aligned.

Best Regards
Panayiotis Savva

**Comment by PaulBallmann** [comment]
Please open for Android as iOS implementation is according to spec.
