### ISSUE TITLE
SecureStorage: Missing argument for parameter 'fileName' in call

### ISSUE THREAD

**Issue by stefanoschrs** [eu-digital-green-certificates/dgca-wallet-app-ios#82]
The storage [initialization](https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/blob/main/DGCAWallet/Models/LocalData.swift#L58) is missing the fileName parameter as requested in the [app-core](https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/main/Sources/Services/SecureStorage.swift#L46) constructor.

Causing XCode to complain and not build

**Comment by alexchornyi** [comment]
@stefanoschrs fixed in #83

**Comment by alexchornyi** [comment]
@stefanoschrs Fixed
