### ISSUE TITLE
Typing errors in certificate validity check text

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-ios#86]
## Describe the bug
![image](https://user-images.githubusercontent.com/81565834/125254985-48bdd080-e2fb-11eb-9707-2e61e314599a.png)

Please correct the typing errors:

certifivate -> certificate
couintry -> country

## Technical details

- iOS wallet app 1.1.0

**Comment by alexchornyi** [comment]
@kerstin-oppermann-tsi fixed and will be available on the next build

**Comment by kerstin-oppermann-tsi** [comment]
is fixed in release 1.1.0(tst)
