### ISSUE TITLE
iOS - Typing Error in Failed Rule Restriction Screen

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-wallet-app-ios#87]
## Describe the bug

Please fix the following typing error:

**if** --> **is**

## Technical details
Wallet App 1.1.0
![wallet_typo](https://user-images.githubusercontent.com/76050122/125425836-d6da8eea-036d-4042-921b-424d38ef2215.jpg)

iPhone 8 plus v. Lutz, iOS 14.4

**Comment by alexchornyi** [comment]
@RalicaY fixed and will be available in the next build

**Comment by kerstin-oppermann-tsi** [comment]
fixed in release 1.1.0(tst)
