### ISSUE TITLE
iOS - TAN input should to be the first after scanning the QR Code before displaying the values of the certificate

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-ios#90]
**## Describe the bug**

When I scan a QR Code at next step should be asked for TAN input without displaying any information about the certificate. before
Steps should be like in Android wallet app.

**## Expected behaviour**

Steps like in Android wallet app:
![image](https://user-images.githubusercontent.com/81565834/125786656-233bbf3a-767e-4d0a-8365-ffe759976fa7.png)
![image](https://user-images.githubusercontent.com/81565834/125786697-76a32325-8fd8-44c0-b0bc-1535db57f8ca.png)
![image](https://user-images.githubusercontent.com/81565834/125786904-9c803bd3-0c41-4b74-8168-a317a2d47792.png)

**Actual behaviour**

all values of the cert are shown before claiming the certificate

**Comment by alexchornyi** [comment]
@kerstin-oppermann-tsi not a bug. We can't validate TAN and after that send this TAN to claim certificate. TAN may used only ones. BE side not ready for this functionality.

**Comment by kerstin-oppermann-tsi** [comment]
@alexchornyi But on Android it works like in the screenshots shown. 

1. At first tthe QR Code is scanned.
2. Then without displaying any infos of the cert the TAN has to put in.
3. And when then TAN is correct **then** all infos of the cert are displayed.

This is the behaviour we discussed in the test team to have similiar in both apps.

**Comment by PaulBallmann** [comment]
@kerstin-oppermann-tsi - Afaik the behaviour on iOS is according to spec, on Android it is not. So maybe we should align Android to the iOS implementation then?

**Comment by kerstin-oppermann-tsi** [comment]
@PaulBallmann yes we discussed this with Hendrik yesterday, I will put this ticket to Android for fixing.
