### ISSUE TITLE
iOS - Validity check button should only be displayed for an already claimed certificate

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-wallet-app-ios#91]
## Describe the bug

Validity check should only be possib´le for already claimed certificates and not during the scanning of new QR Code.

**Possible fix:**
Please remove the valitity chexck button when scanning the QR Code. 

Only provide the Save button. 

But depending on the issue https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/90 display the values of the cert and the SAVE button only after entering the correct TAN.

**Comment by alexchornyi** [comment]
@kerstin-oppermann-tsi fixed in #94 please validate and close

**Comment by kerstin-oppermann-tsi** [comment]
fixed in release 1.1.0
