### ISSUE TITLE
High Urgency: Certificates are lost after an update via AppStorr

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-wallet-app-ios#96]
Upon releasing an app update via the Apple Store, the Certificates that were saved on the device prior to the update are lost.

Multiple reports have been given from the AppStore review and on Twitter.

Please treat this as urgent.

Best Regards
Panayiotis Savva 
Cyprus.

**Comment by psavva** [comment]
I will close the issue as we know this originates from a missing old fix (storage)

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment]
Perfect! I am glad that the problem could be solved.
We were also not able to reproduce the issue.
